name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Echo secrets
      run: echo '${{ toJson(github.event.pull_request.base) }}'
      if: github.event_name == 'pull_request'
      
